### PR TITLE
Always include currency in prices

### PR DESCRIPTION
**Pull request by pamil**
Closes #203, closes #204.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Tests are failing.

**Comment by lchrusciel** [comment]
I'm ok with this change but I'm not sure if it is necessary. We have a currency on a cart and it is not possible to have price in a different currency.

**Comment by pamil** [comment]
@lchrusciel it's also for product variants

**Comment by pjedrzejewski** [comment]
@lchrusciel It makes frontend's life a bit easier because the price structure is consistent.

**Comment by pjedrzejewski** [comment]
Thanks Kamil!

**Pull request merged**
