### PR TITLE
[Checkout] Complete order

### LINKED ISSUE #24: As a Customer, I want to complete my checkout
* The "complete" step of checkout

```
PUT /cart/{token}/checkout/complete
```

Parameters:

* Notes (optional)

### PR DESCRIPTION
**Pull request by lchrusciel**
Resolves #24

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@lchrusciel Require rebasing.

**Comment by lchrusciel** [comment]
@pjedrzejewski done

**Comment by pjedrzejewski** [comment]
@lchrusciel One more due to config changes. :/ :P

**Comment by pjedrzejewski** [comment]
👍

**Pull request merged**
